blueprint:
  name: Warnung - Nuki verriegelt aber Tür offen
  description: >-
    Sendet eine Warnung, wenn das Nuki-Schloss verriegelt wurde, aber der Türkontakt meldet, dass die Tür noch offen ist.
  domain: automation
  input:
    nuki_lock:
      name: Nuki Smart Lock
      description: Das Schloss-Entity, z. B. lock.nuki_haustuer
      selector:
        entity:
          domain: lock
    door_sensor:
      name: Türkontakt (binary_sensor)
      description: Der Tür-/Fensterkontakt, der „offen/geschlossen“ meldet
      selector:
        entity:
          domain: binary_sensor
    notify_target:
      name: Benachrichtigung
      description: Service oder Gerät für die Push-Nachricht (z. B. notify.mobile_app_xyz)
      selector:
        entity:
          domain: notify
          multiple: false
    media_player:
      name: Media Player (optional)
      description: Gerät, das Ansagen oder Sounds abspielen kann
      default: []
      selector:
        entity:
          domain: media_player
trigger:
  - platform: state
    entity_id: !input nuki_lock
    to: "locked"
condition:
  - condition: state
    entity_id: !input door_sensor
    state: "on"
action:
  - service: notify.notify
    data:
      message: "⚠️ Das Schloss wurde verriegelt, aber die Tür ist noch offen!"
  - choose:
      - conditions: "{{ media_player | length > 0 }}"
        sequence:
          - service: tts.google_say
            target:
              entity_id: !input media_player
            data:
              message: "Bitte überprüfe die Haustür, sie ist noch offen!"
mode: single